
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: Pa55word

development:
  <<: *default
  database: email_text_development
  
test:
  <<: *default
  database: email_text_test

production:
  <<: *default
  host: <%= ENV["MARKETING_HOST"] { localhost } %>
  port: <%= ENV["MARKETING_PORT"] { 5432 } %>
  url: <%= ENV["MARKETING_APP_DATABASE_URL"] %>
